// © SS220, MIT full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/MIT_LICENSE.TXT

using Content.Shared.Materials;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Materials;
using Content.Client.Message;
using Robust.Shared.Utility;

namespace Content.Client.SS220.ResourceMiner;

[GenerateTypedNameReferences]
public sealed partial class ResourceMinerWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly MaterialStorageSystem _materialStorage = default!;

    public event Action<int>? OnChangeSiloOption;
    public event Action? OnRequestSilos;

    public ResourceMinerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _materialStorage = IoCManager.Resolve<EntityManager>().System<MaterialStorageSystem>();

        NetSiloOptions.OnItemSelected += (args) =>
        {
            OnChangeSiloOption?.Invoke(args.Id);
            NetSiloOptions.SelectId(args.Id);
        };
        UpdateButton.OnPressed += (_) => OnRequestSilos?.Invoke();
    }

    public void SetAvailableSilos(HashSet<NetEntity> silos, NetEntity? chosenSilo)
    {
        NetSiloOptions.Clear();

        NetSiloOptions.AddItem("-", EntityUid.Invalid.Id);

        foreach (var silo in silos)
        {
            NetSiloOptions.AddItem(silo.ToString(), silo.Id);
        }

        if (chosenSilo is null)
            return;

        NetSiloOptions.SelectId(chosenSilo.Value.Id);
    }

    public void SetTimeBetweenUpdate(TimeSpan timeBetweenUpdate)
    {
        MaterialInfoTitle.Text = Loc.GetString("resource-miner-window-generation-title", ("Seconds", timeBetweenUpdate.TotalSeconds));
    }

    public void SetGenerationAmount(Dictionary<ProtoId<MaterialPrototype>, int> generationAmount)
    {
        MaterialInfoContainer.RemoveAllChildren();

        foreach (var (materialId, generationVolume) in generationAmount)
        {
            if (!_prototype.Resolve(materialId, out var materialPrototype))
                continue;

            var nameNode = FormattedMessage.Empty;
            nameNode.PushColor(materialPrototype.Color);
            nameNode.AddText(Loc.GetString(materialPrototype.Name));
            nameNode.Pop();

            var volume = (float)generationVolume / _materialStorage.GetSheetVolume(materialPrototype);

            var locText = Loc.GetString("resource-miner-generation-label", ("Name", nameNode.ToMarkup()), ("Volume", volume));
            var label = new RichTextLabel();
            label.SetMarkup(locText);

            MaterialInfoContainer.AddChild(label);
        }
    }
}
